HW2 is completed (base)
SelferRy/otus_gopro pull request #2
Opened 2024-10-13 21:37 UTC by SelferRy

Solved basic version of hw02 task.

2024-10-13 23:28 UTC, SelferRy commented
Added backslash part

2024-10-17 21:38 UTC, ityulkanov requested changes
Набросал замечания, посмотрите пожалуйста как будет время

2024-10-17 21:38 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +}
main вам тут ни к чему - для этогого есть тесты
```suggestion

```

2024-10-17 21:38 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +}
тут вы вызываете strconv.Atoi который преобразует (конвертирует) строку в число. оверхед невелик, но имхо понятнее было бы  <= rune <=

2024-10-17 21:38 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +func firstIsDigit(first rune) bool {
нарушен DRY - полностью повторяет isDigit

2024-10-17 21:38 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +func lastElem(i int, count int) bool {
предлагаю заинлайнить

2024-10-17 21:38 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +func isBackslash(r rune) bool {
то же самое что и в функциях выше, oneliner который понятнее было бы использовать внутри unpack

2024-10-17 21:38 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +package main
название модуля менять нельзя

2024-10-17 21:38 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +func takeTimes(num rune) int {
то же замечание - можно убрать функцию, она не несёт полезных функций

2024-10-17 21:38 UTC, ityulkanov commented on hw02_unpack_string/unpack_test.go
> +package main
название модуля менять нельзя

2024-10-17 21:38 UTC, ityulkanov commented on hw02_unpack_string/unpack_test.go
>  	invalidStrings := []string{"3abc", "45", "aaa10b"}
посмотрите, почему некорректно отрабатывает следующий тест кейс "ghhj\\б2"

2024-10-17 21:38 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +		case matchBackslash(s[i], s[i+1]):
вложенные case - switch очень сложны для понимания.  В идеале было бы обойтись без него. в целом тут достаточно нескольких if - else

2024-10-24 09:38 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +}
Переделал

2024-10-24 09:38 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +func firstIsDigit(first rune) bool {
Переделал

2024-10-24 09:43 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +func lastElem(i int, count int) bool {
1. Функция выделяет логический блок - помогает не вникать каждый раз в низкоуровневый код, который не говорит о сути происходящего. 
2. Функция объясняет что происходит своим названием, позволяет не думать о несущественных деталях на том уровне абстракции, где используется.
3. Функцию можно явно протестировать.
4. Функция расположена локально в данном модуле и является приватной - т.е. не увеличивает как-либо значимо сложность кода и плюсы достаются "бесплатно".

Считаю, что лучше оставить, т.к. повышает читабельность и согласованность данного модуля.

2024-10-24 09:45 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +func isBackslash(r rune) bool {
Могу повторить аргументацию из блока выше и добавить, что:
5. Данная функция неоднократно переиспользуется, что подчёркивает общность + протестировав её однажды гарантируем правильное выполнение каждого блока (ошибки встречаются и в банальных вещах).

2024-10-24 09:46 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +package main
Вернул

2024-10-24 09:48 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +func takeTimes(num rune) int {
Могу повторить аргументы выше и добавить:
6. Данная функция менее тривиальна, чем предыдущие.
7. В местах, где она используется, мне не нужны детали: какая внешняя либа, ошибка, как всё записывается и т.п.
8. Данная функция содержит зависимость от библиотеки (пусть и стандартной), которая скрывается.

2024-10-24 09:48 UTC, SelferRy commented on hw02_unpack_string/unpack_test.go
> +package main
Вернул

2024-10-24 09:50 UTC, SelferRy commented on hw02_unpack_string/unpack_test.go
>  	invalidStrings := []string{"3abc", "45", "aaa10b"}
Посмотрел. Добавил в тесты

2024-10-24 09:55 UTC, SelferRy commented on hw02_unpack_string/unpack.go
> +		case matchBackslash(s[i], s[i+1]):
Вынес данную логику. 
Преимущество в читабельности if перед switch в случае > 2 альтернатив нет. 
Могут быть плюсы в механике (когда надо неск условий проверить и сделать что-то не по 1, а по неск условиям и действия независимы - это тоже, кстати, усложняет чтение). Или чтобы переменные ввести для/на время проверки.
В данном случае эти механики не используются и switch используется как более легковесная и прямолинейная альтернатива if + if else + else.

2024-10-24 09:56 UTC, SelferRy commented
> Набросал замечания, посмотрите пожалуйста как будет время

ответил по замечаниям

2024-10-24 18:45 UTC, ityulkanov approved these changes

2024-10-24 21:39 UTC, merged